run:
  timeout: 5m
output:
  sort-results: true
linters:
  enable-all: true
  disable:
    - cyclop # need large switch statements over protreflect.Kind
    - execinquery # deprecated: archived by owner
    - exhaustruct # zero values of fields should be respected
    - exhaustive # does not treat default as exhaustive
    - exportloopref # deprecated: no longer relevant, replaced by copyloopvar
    - funlen # redundant with cyclop
    - gocognit # redundant with cyclop
    - gofumpt # prefer standard gofmt
    - goimports # rely on gci instead
    - gomnd # deprecated: renamed mnd
    - ireturn # useful for
    - maintidx # redundant with cyclop
    - nlreturn # stylistic choice
    - nonamedreturns # yes, named returns
    - testpackage # not necessary
    - wsl # stylistic choice
    - wrapcheck # don't always need to wrap errors
linters-settings:
  nolintlint:
    require-specific: true
    require-explanation: true
    allow-unused: false
  depguard:
    rules:
      main:
        files: [$all]
        deny:
          - pkg: "^log$"
            desc: use log/slog exclusively
issues:
  exclude-rules:
    # loosen restrictions on test code
    - path: '_test.go$'
      linters:
        - cyclop
        - dupl
        - varnamelen
        - funlen
        - lll
