version: "2"
linters:
  default: all
  disable:
    - cyclop # need large switch statements over protoreflect.Kind
    - exhaustive # zero values of fields should be respected
    - exhaustruct # does not treat default as exhaustive
    - funlen # redundant with cyclop
    - gocognit # redundant with cyclop
    - ireturn # required to satisfy slog.Handler interface
    - maintidx # redundant with cyclop
    - nlreturn # stylistic choice
    - nonamedreturns # yes, named returns
    - testpackage # not necessary
    - wrapcheck # don't always need to wrap errors
    - wsl # stylistic choice
  settings:
    depguard:
      rules:
        main:
          files:
            - $all
          deny:
            - pkg: ^log$
              desc: use log/slog exclusively
    nolintlint:
      require-explanation: true
      require-specific: true
      allow-unused: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - dupl
          - lll
          - varnamelen
        path: _test.go$
formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/rodaine/protoslog
  exclusions:
    generated: lax
